# Generated by Django 4.2.6 on 2023-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=True)),
                ('location', models.JSONField()),
                ('start_time', models.DateTimeField()),
                ('danger', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
            ],
        ),
    ]
